### ISSUE TITLE
Версия Python

### ISSUE THREAD

**Issue by kozintsev** [Weltraum/Article-Python-in-aid-of-the-designer.-Tames-API-Kompas-3D.#1]
Какую версию Python вы использовали? И какую можно или нужно использовать?
Может стоит добавить эту информацию в текст?

**Comment by Weltraum** [comment]
Использовал Python 3.5, это написано в начале статьи. Но данный код легко переписать на Python 2, т.к. никаких серьёзных зависимостей мной не использовано. Единственное на что стоит обратить внимание, это на модуль tkinter:

```
# для версии python 3.0 и выше
from tkinter import Tk
from tkinter.filedialog import askopenfilenames

# для версии python 2.7 и ниже
from Tkinter import Tk
from Tkinter.tkFileDialog import askopenfilenames
```

**Comment by kozintsev** [comment]
Спасибо за информацию
